name: Build-sphinx-doc

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ghp-import

      - name: Build HTML
        run: |
          sphinx-build docs docs/_build/html

      - name: Run ghp-import to generate GitHub Pages
        run: |
          ghp-import -npfo docs/_build/html